spring.application.name=whodo-backend
server.port = 443
server.tomcat.protocol-header=x-forwarded-proto

# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/dev_spring_security
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/realms/dev_spring_security/protocol/openid-connect/certs
