spring.application.name=whodo-backend
server.port = 80
server.tomcat.protocol-header=x-forwarded-proto

jwt.SECRET = my57638792F423F4428472secretB4B6250655368566D597key133743677397A2443264629
jwt.ExpirationMs = 8640000

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=create-drop

# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/dev_spring_security
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/realms/dev_spring_security/protocol/openid-connect/certs
